# Config file for the acts_as_solr plugin.
#
# If you change the host or port number here, make sure you update 
# them in your Solr config file

development:
  url: http://127.0.0.1:8982/solr
  
production:
  url: http://127.0.0.1:8983/solr
  # 64bitç‰ˆ
  # jvm_options: -server -d64 -Xmx1024M -Xms64M
  jvm_options: -server -Xmx1024M -Xms64M

test:
  url: http://127.0.0.1:8981/solr

